repos:
  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.0
    hooks:
      - id: go-mod-tidy
      - id: go-fmt
      - id: go-vet
      - id: golangci-lint
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.24.0
    hooks:
      - id: eslint
        files: '^frontend/src'
        types: []
        types_or: [javascript, vue]
        args:
          - --fix
