// Code generated by "stringer -type EmailStatus -linecomment"; DO NOT EDIT.

package models

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EmailStatusNone-0]
	_ = x[EmailStatusSent-1]
	_ = x[EmailStatusEmailOpened-2]
	_ = x[EmailStatusWebsiteOpened-3]
}

const _EmailStatus_name = "NoneSentEmail OpenedWebsite Opened"

var _EmailStatus_index = [...]uint8{0, 4, 8, 20, 34}

func (i EmailStatus) String() string {
	if i >= EmailStatus(len(_EmailStatus_index)-1) {
		return "EmailStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EmailStatus_name[_EmailStatus_index[i]:_EmailStatus_index[i+1]]
}
