// Code generated by "stringer -type AuthMethod -linecomment"; DO NOT EDIT.

package models

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AuthMethodBasic-0]
	_ = x[AuthMethodHeader-1]
}

const _AuthMethod_name = "basicheader"

var _AuthMethod_index = [...]uint8{0, 5, 11}

func (i AuthMethod) String() string {
	if i >= AuthMethod(len(_AuthMethod_index)-1) {
		return "AuthMethod(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _AuthMethod_name[_AuthMethod_index[i]:_AuthMethod_index[i+1]]
}
