// Code generated by "stringer -type PrivacyMode -linecomment"; DO NOT EDIT.

package models

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PrivacyModePrivate-0]
	_ = x[PrivacyModePublic-1]
}

const _PrivacyMode_name = "privatepublic"

var _PrivacyMode_index = [...]uint8{0, 7, 13}

func (i PrivacyMode) String() string {
	if i >= PrivacyMode(len(_PrivacyMode_index)-1) {
		return "PrivacyMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PrivacyMode_name[_PrivacyMode_index[i]:_PrivacyMode_index[i+1]]
}
